<?xml version="1.0" encoding="UTF-8" standalone="no"?><testsuite errors="0" failures="2" name="Task Management" skipped="0" tests="3" time="25.81" timestamp="2023-07-25 03:49:59"><testcase name="Add Task Management Success"/><testcase name="Edit Task Management"><failure message="&#13;&#10;expected: &quot;Data has been saved successfull&quot;&#13;&#10; but was: &quot;Data has been saved successfully.&quot;" type="org.opentest4j.AssertionFailedError">&#13;
expected: "Data has been saved successfull"&#13;
 but was: "Data has been saved successfully."</failure><system-err>&#13;
expected: "Data has been saved successfull"&#13;
 but was: "Data has been saved successfully."&#13;
cucumber.starter@1.0.0-SNAPSHOT/vmo.pages.taskmanagement.TaskVerify.messageSuccessShouldContain(TaskVerify.java:51)&#13;
cucumber.starter@1.0.0-SNAPSHOT/vmo.steps.TaskManagementStepDefinitions.systemShowsSuccessMessage(TaskManagementStepDefinitions.java:90)&#13;
✽.System shows success message should be "Data has been saved successfull"(file:///C:/project/serenity-cucumber-starter/src/test/resources/features/taskManagement/TaskManagement.feature:26)&#13;
</system-err></testcase><testcase name="Delete Task Management"><failure message="&#13;&#10;expected: &quot;Delete successfully&quot;&#13;&#10; but was: &quot;Delete successfully!&quot;" type="org.opentest4j.AssertionFailedError">&#13;
expected: "Delete successfully"&#13;
 but was: "Delete successfully!"</failure><system-err>&#13;
expected: "Delete successfully"&#13;
 but was: "Delete successfully!"&#13;
cucumber.starter@1.0.0-SNAPSHOT/vmo.pages.taskmanagement.TaskVerify.messageSuccessShouldContain(TaskVerify.java:51)&#13;
cucumber.starter@1.0.0-SNAPSHOT/vmo.steps.TaskManagementStepDefinitions.systemShowsSuccessMessage(TaskManagementStepDefinitions.java:90)&#13;
✽.System shows success message should be "Delete successfully"(file:///C:/project/serenity-cucumber-starter/src/test/resources/features/taskManagement/TaskManagement.feature:39)&#13;
</system-err></testcase></testsuite>